### ISSUE TITLE
Custom config.yml locations

### ISSUE THREAD

**Issue by tpakeman** [josephaxisa/henry#3]
The default behaviour in henry is to create the config.yml file in the current working directory. This could be confusing for some users. It would be great to create a config.yml file in the default install folder and then allow users to override this either globally or on a per-use basis.

**Comment by josephaxisa** [comment]
Users can specify the path to the config.yml file using the `--path` option. Requiring the users to place the config file inside the site-packages directory (which is the default target directory of manually built python packages) is not very user friendly since it's not easy to locate at all. Note that I say that it requires users to place it because the config file is not something that can be auto generated as it requires users to put their API3 credentials in.
